name: siresma
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  get_cli: ^1.8.1
  google_fonts: ^4.0.4
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_nav_bar: ^5.0.6
  intl: ^0.17.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
  uses-material-design: true

