name: siresma
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  get_cli: ^1.8.1
  google_fonts: ^4.0.4
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.0.0
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1
  persistent_bottom_nav_bar: any
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  otp_text_field: ^1.1.3
  flutter_datetime_picker: ^1.5.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.11
  flutter_secure_storage: ^8.1.0
  dio: ^4.0.0



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
  uses-material-design: true

